name: undone
version: 0.2.15-dev
description: A library for undo and redo.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/undone
documentation: http://rmsmith.github.com/undone/undone.html
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  bench: '>=0.2.18'
  browser: '>=0.9.0'   
  unittest: '>=0.9.0'
