name: undone
version: 0.2.6-dev
description: A library for undo and redo.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/undone
documentation: http://rmsmith.github.com/undone/undone.html
dependencies:
  logging: '>=0.6.19'
dev_dependencies:
  bench: '>=0.2.7'
  browser: '>=0.6.19'   
  unittest: '>=0.6.19'
