name: undone
version: 0.2.12
description: A library for undo and redo.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/undone
documentation: http://rmsmith.github.com/undone/undone.html
dependencies:
  logging: '>=0.8.10'
dev_dependencies:
  bench: '>=0.2.17'
  browser: '>=0.8.10'   
  unittest: '>=0.8.10'
