name: undone
version: 0.2.8
description: A library for undo and redo.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/undone
documentation: http://rmsmith.github.com/undone/undone.html
dependencies:
  logging: '>=0.7.1'
dev_dependencies:
  bench: '>=0.2.9'
  browser: '>=0.7.1'   
  unittest: '>=0.7.1'
